--DROP TABLE portfolio IF EXISTS;

CREATE TABLE portfolio (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY(START WITH 1, INCREMENT BY 1) PRIMARY KEY,
  stock_count INTEGER,
  price DECIMAL(10,2),
  change DECIMAL(10,2),
  symbol VARCHAR(30),
  name VARCHAR(130),
  currency VARCHAR(10),
  updated TIMESTAMP
);